### ISSUE TITLE
Link Visitor broken as of v5.0

### ISSUE THREAD

**Issue by UnstableStranger** [kinitawowi/linkvisitor-firefox#1]
UPDATE: I didn't notice this at first but what's actually happening when I click Mark all links as visited is that CPU usage goes up to 16%-17% for about 20 seconds and then, ever so slowly, it marks one link at a time as read. It took six minutes to mark one page of /r/AskReddit as read and then CPU usage returned to normal. It used to be a really quick process on the order of a few seconds.

First, thanks very much for updating Link Visitor.

Second, I received an update to Link Visitor v5.0 today. Marking links as visited no longer works. Plus, Firefox v55.0.3 is now using 16% of my 32GB of RAM on Windows 10 Pro. When I disable Link Visitor RAM usage drops to the usual 2%.

**Comment by kinitawowi** [comment]
I've pushed another update,  which now includes a displays the progress when marking links,  however, there are other refresh issues handled by Firefox itself which I cannot influence.

On the speed front, there's a trade off that's required to mark the links as quick as possible (which increases CPU usage) while keeping the UI responsive.  The plugins default work rate marks 10 links a second,  but is subject to any delays in FF which may impact this.    Firefox's own history window and other plugins watching the history can cause additional delays.

On the memory front,  I'm not seeing any unusual memory usage with and without the plugin enabled or installed.  However, as above, any other plugins interacting with history and Firefox's own caching could be affected by marking links visited as all the links get added to the history.

**Comment by UnstableStranger** [comment]
v5.1 is even slower. Rather than marking 10 links per second as you mentioned, it's actually marking one link every 10 seconds. When I get home later I'll disable all my other extensions to see if Link Visitor is being affected by one of them.

**Comment by UnstableStranger** [comment]
Hi again. After disabling all my extensions the problem persisted.

**Comment by kinitawowi** [comment]
My only other thought is that your history has a significant number of links in it,  impacting Firefoxs performance when marking links.  You could try loading Firefox with a new profile to check.

I've also reduced the default delay between marking individual links to 10ms  (this is now configurable in the preferences).

I've also added a second option to remove the check to see if the link is already in the history.  If the 'skip history check' option is enabled, there is one API call per link to add it to the history and the time taken is purely down to the performance of Firefoxs API.
